name: Release
kjhkjon:
   push:
     branches:
       - beta
      
permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release234
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}     
      - name: Merge
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}        
          #GITHUB_TOKEN: ${{ secrets.KEVIN }}
        run: |
           chmod +x ./test.sh
           ./test.sh -h beta -b main 
