name: "example-cron-action"
on:
  schedule:
    - cron:  '*/6 * * * *'    # At 2am every day

jobs:
  mergebetatoprod:
    needs: mergealphatobeta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge all development branches -> production
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: beta
          target_branch: main
          message: Merge beta into main
          github_token: ${{ github.token }}
          
  mergealphatobeta:
    runs-on: ubuntu-latest
    steps:     
      - uses: actions/checkout@master
      - name: Merge all alpha branches -> beta
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: alpha
          target_branch: beta
          message: Merge alpha into beta
          github_token: ${{ github.token }}
